import type { Workout } from '../db/entities';
type Props = { workouts: Workout[]; onStartWorkout: () => void; onNavigate: (section: 'history' | 'exercises' | 'templates') => void };
const formatDate = (date: string) => new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'short' }).format(new Date(date));
export function DashboardPage({ workouts, onStartWorkout, onNavigate }: Props) {
  return <section className="content-page dashboard-page" aria-labelledby="dashboard-title">
    <header className="page-header dashboard-header"><div><p className="eyebrow">Личный журнал</p><h1 id="dashboard-title" aria-label="Обзор">Твоя тренировка<br /><span>начинается здесь.</span></h1><p className="muted">Быстрая запись. Полный контроль. Ничего лишнего.</p></div></header>
    <button className="hero-start" type="button" aria-label="Начать тренировку" onClick={onStartWorkout}><span className="hero-glow" aria-hidden="true" /><span className="hero-icon" aria-hidden="true">＋</span><span className="hero-copy"><em>Новая сессия</em><strong>Начать тренировку</strong><small>Выбери шаблон или начни с чистого листа</small></span><span className="hero-arrow" aria-hidden="true">→</span></button>
    <div className="quick-grid" aria-label="Быстрый доступ"><button type="button" onClick={() => onNavigate('exercises')}><span className="quick-icon" aria-hidden="true">01</span><span><strong>Упражнения</strong><small>Твой личный справочник</small></span><span aria-hidden="true">↗</span></button><button type="button" onClick={() => onNavigate('templates')}><span className="quick-icon" aria-hidden="true">02</span><span><strong>Шаблоны</strong><small>Готовые планы тренировок</small></span><span aria-hidden="true">↗</span></button></div>
    <div className="section-heading"><div><p className="eyebrow">Журнал</p><h2>Последние тренировки</h2></div><button className="text-button" type="button" onClick={() => onNavigate('history')}>Открыть историю <span aria-hidden="true">→</span></button></div>
    <div className="recent-list">{workouts.slice(0, 3).map((workout, index) => <button className="recent-item" type="button" key={workout.id} onClick={() => onNavigate('history')}><span className="recent-mark">{String(index + 1).padStart(2, '0')}</span><span className="recent-copy"><strong>{workout.templateId ? 'Тренировка по шаблону' : 'Свободная тренировка'}</strong><small>{formatDate(workout.date)} <i /> {workout.exercises.length} упражнений</small></span><span className="recent-chevron" aria-hidden="true">→</span></button>)}{workouts.length === 0 && <div className="empty-state"><span aria-hidden="true">＋</span><strong>Здесь появится твой журнал</strong><p>Заверши первую тренировку — мы аккуратно сохраним её на этом устройстве.</p><button className="empty-action" type="button" onClick={onStartWorkout}>Начать сейчас</button></div>}</div>
  </section>;
}
